# Generated by Django 3.0.2 on 2020-02-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualtotalload',
            name='Status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='aggregatedgenerationpertype',
            name='Status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dayaheadtotalloadforecast',
            name='Status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
